name: NuGet Package Release

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v5

            # Setup .NET Core SDK
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: 10.0.x

            - name: Pack ShellToolkit
              run: dotnet pack --configuration Release --output ./artifacts src/Larcanum/ShellToolkit/ShellToolkit.csproj

            - name: Pack ShellToolkit.Terminal
              run: dotnet pack --configuration Release --output ./artifacts src/Larcanum/ShellToolkit.Terminal/ShellToolkit.Terminal.csproj

            # Push the packages to NuGet
            - name: Push to NuGet
              env:
                  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
              run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
